export const data = [
  {
    productName: "Ceramic Soap Dish",
    price: 9.99,
    craftsperson: "Ceramics Artisan",
    color: "White",
    availability: true,
    image: "./assets/CeramicSoapDish.jpg",
    category: "bathroom",
    description:
      "Enhance your bathroom decor with this beautifully crafted ceramic soap dish. Handmade by a skilled ceramics artisan, it features a clean white color and a sleek design. A perfect addition to your bathroom ensemble.",
  },
  {
    productName: "Carpets",
    price: 199.99,
    craftsperson: "Rug Weaver",
    color: "Various",
    availability: true,
    image: "./assets/MoroccanCarpets.jpg",
    category: "decor",
    description:
      "Elevate your living space with these intricately woven Moroccan carpets. Each carpet is a masterpiece crafted by a skilled rug weaver, featuring a variety of captivating colors and traditional patterns. A blend of culture and comfort.",
  },
  {
    productName: "Ceramic Jar",
    price: 24.99,
    craftsperson: "Ceramics Artisan",
    color: "Blue",
    availability: true,
    image: "./assets/CeramicJar.jpg",
    category: "kitchen",
    description:
      "Store your kitchen essentials in style with this charming ceramic jar. Handcrafted by a talented ceramics artisan, its soothing blue hue and unique design add a touch of elegance to your kitchen decor.",
  },
  {
    productName: "Candles Box",
    price: 12.99,
    craftsperson: "Candle Maker",
    color: "Assorted",
    availability: true,
    image: "./assets/CandlesBox.jpg",
    category: "decor",
    description:
      "Set the mood with these delightful Moroccan-inspired candles. Handcrafted by a dedicated candle maker, the set includes an assortment of scented candles in vibrant colors. Perfect for adding a warm glow to any space.",
  },
  {
    productName: "Ceramic Bowl",
    price: 14.99,
    craftsperson: "Ceramics Artisan",
    color: "Turquoise",
    availability: true,
    image: "./assets/CeramicBowl.jpg",
    category: "kitchen",
    description:
      "Enjoy your meals in this beautifully glazed ceramic bowl. Handcrafted by a skilled ceramics artisan, its vibrant turquoise color and hand-painted accents make every dining experience special.",
  },
  {
    productName: "Ceramic Plate",
    price: 9.99,
    craftsperson: "Ceramics Artisan",
    color: "Green",
    availability: true,
    image: "./assets/CeramicPlate.jpg",
    category: "kitchen",
    description:
      "Serve your culinary creations on this exquisite ceramic plate. Handcrafted by a talented ceramics artisan, its lush green color and intricate design make it a statement piece for your dining table.",
  },
  {
    productName: "Tajin",
    price: 49.99,
    craftsperson: "Ceramics Artisan",
    color: "Brown",
    availability: true,
    image: "./assets/Tajin.jpg",
    category: "kitchen",
    description:
      "Cook up delicious and authentic Moroccan dishes in this traditional tajin. Handcrafted by a skilled ceramics artisan, its brown color and glazed finish bring the essence of Moroccan cooking to your kitchen.",
  },
  {
    productName: "Traditional shoes",
    price: 29.99,
    craftsperson: "Shoemaker",
    color: "Brown",
    availability: true,
    image: "./assets/TraditionalShoes.jpg",
    category: "apparel",
    description:
      "Step into Moroccan tradition with these handcrafted leather shoes. Expertly made by a skilled shoemaker, these brown shoes showcase traditional design and unmatched comfort. A perfect blend of style and heritage.",
  },
  {
    productName: "Massage Accessories",
    price: 39.99,
    craftsperson: "Massage Therapist",
    color: "Various",
    availability: true,
    image: "./assets/MassageAccessories.jpg",
    category: "health",
    description:
      "Indulge in self-care with these carefully crafted Moroccan massage accessories. Created by a skilled massage therapist, the set includes various tools to enhance relaxation and rejuvenation.",
  },
  {
    productName: "Kitchen Tails",
    price: 8.99,
    craftsperson: "Textile Artisan",
    color: "Multi-colored",
    availability: true,
    image: "./assets/KitchenTails.jpg",
    category: "kitchen",
    description:
      "Add a pop of color to your kitchen with these vibrant Moroccan-inspired kitchen towels. Handwoven by a talented textile artisan, they're not only functional but also a feast for the eyes.",
  },
  {
    productName: "Toothbrush Tumbler",
    price: 5.99,
    craftsperson: "Ceramics Artisan",
    color: "White",
    availability: true,
    image: "./assets/ToothbrushTumbler.jpg",
    category: "bathroom",
    description:
      "Organize your bathroom essentials in this handy ceramic toothbrush tumbler. Skillfully crafted by a ceramics artisan, its clean white color and minimalist design complement any bathroom decor.",
  },
  {
    productName: "Rugs",
    price: 179.99,
    craftsperson: "Rug Weaver",
    color: "Various",
    availability: true,
    image: "./assets/MoroccanRugs.jpg",
    category: "decor",
    description:
      "Transform your living space with these handwoven Moroccan rugs. Each rug is a work of art crafted by a skilled rug weaver, showcasing a blend of traditional patterns and contemporary style.",
  },
  {
    productName: "Tea Pod",
    price: 19.99,
    craftsperson: "Ceramics Artisan",
    color: "Blue",
    availability: true,
    image: "./assets/TeaPod.jpg",
    category: "kitchen",
    description:
      "Brew your favorite tea in style with this Moroccan-inspired ceramic tea pod. Handcrafted by a talented ceramics artisan, its soothing blue color and unique design make tea time a delightful experience.",
  },
  {
    productName: "Chocolate Basket Gift",
    price: 29.99,
    craftsperson: null,
    color: "Brown",
    availability: true,
    image: "./assets/ChocolateBasketGift.jpg",
    category: "gift",
    description:
      "Surprise your loved ones with this delightful chocolate basket gift. A selection of the finest Moroccan chocolates beautifully arranged in a brown basket. A sweet gesture for any occasion.",
  },
  {
    productName: "Saffron Jar",
    price: 12.99,
    craftsperson: "Spice Expert",
    color: "Yellow",
    availability: true,
    image: "./assets/SaffronJar.jpg",
    category: "kitchen",
    description:
      "Add a touch of luxury to your dishes with this Moroccan saffron jar. Sourced and packaged by a skilled spice expert, its vibrant yellow threads bring flavor and color to your culinary creations.",
  },
  {
    productName: "Brass Accessory",
    price: 17.99,
    craftsperson: "Brass Artisan",
    color: "Brass",
    availability: true,
    image: "./assets/BrassAccessory.jpg",
    category: "decor",
    description:
      "Adorn your space with the elegance of Moroccan brass accessories. Handcrafted by a skilled brass artisan, this piece features intricate designs and a timeless brass finish.",
  },
  {
    productName: "Jewelry Box",
    price: 14.99,
    craftsperson: "Woodworker",
    color: "Brown",
    availability: true,
    image: "./assets/JewelryBox.jpg",
    category: "accessory",
    description:
      "Store your jewelry in this beautifully crafted Moroccan-inspired jewelry box. Handmade by a skilled woodworker, its rich brown color and ornate design add a touch of opulence to your accessory collection.",
  },
  {
    productName: "Silver Jewelry",
    price: 34.99,
    craftsperson: "Silversmith",
    color: "Silver",
    availability: true,
    image: "./assets/SilverJewelry.jpg",
    category: "accessory",
    description:
      "Adorn yourself with the beauty of Moroccan silver jewelry. Meticulously crafted by a skilled silversmith, each piece showcases traditional designs and the elegance of silver.",
  },
  {
    productName: "Tea Pod",
    price: 19.99,
    craftsperson: "Ceramics Artisan",
    color: "Blue",
    availability: true,
    image: "./assets/TeaPod.jpg",
    category: "kitchen",
    description:
      "Brew your favorite tea in style with this Moroccan-inspired ceramic tea pod. Handcrafted by a talented ceramics artisan, its soothing blue color and unique design make tea time a delightful experience.",
  }
];
